package com.shipping.carrier.application;

import com.shipping.events.OrderPacked;
import com.shipping.events.OrderShipped;
import com.shipping.events.TrackingEvent;
import com.shipping.events.TrackingStatus;
import com.shipping.kafka.producer.DomainEventPublisher;
import io.micrometer.core.instrument.MeterRegistry;
import org.apache.camel.ProducerTemplate;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.Map;

@Service
public class ManifestService {

    private static final Logger log = LoggerFactory.getLogger(ManifestService.class);

    private final DomainEventPublisher publisher;
    private final ProducerTemplate camelProducer;
    private final MeterRegistry meterRegistry;

    public ManifestService(DomainEventPublisher publisher,
                           ProducerTemplate camelProducer,
                           MeterRegistry meterRegistry) {
        this.publisher = publisher;
        this.camelProducer = camelProducer;
        this.meterRegistry = meterRegistry;
    }

    /**
     * 1. Build the X12 856 EDI manifest body.
     * 2. Send to Camel route which transmits via SFTP (or local file in dev).
     * 3. Publish OrderShipped and an initial TrackingEvent.
     */
    public void processOrderPacked(OrderPacked event) {
        String ediBody = buildX12_856(event);

        camelProducer.sendBodyAndHeaders("direct:transmit-manifest", ediBody,
            Map.of("shipmentId", event.getShipmentId()));

        // Publish OrderShipped
        OrderShipped shipped = OrderShipped.newBuilder()
            .setOrderId(event.getOrderId().toString())
            .setShipmentId(event.getShipmentId().toString())
            .setTrackingNumber(event.getTrackingNumber().toString())
            .setCarrier(event.getCarrier().toString())
            .setEstimatedDeliveryDate(null)
            .setEventTime(Instant.now().toEpochMilli())
            .build();
        publisher.publish("tracking-events", event.getOrderId().toString(), shipped);

        // Publish initial in-transit tracking event
        TrackingEvent tracking = TrackingEvent.newBuilder()
            .setTrackingNumber(event.getTrackingNumber().toString())
            .setCarrier(event.getCarrier().toString())
            .setStatus(TrackingStatus.IN_TRANSIT)
            .setLocation(null)
            .setDescription("Shipment picked up from FC")
            .setOccurredAt(Instant.now().toEpochMilli())
            .setEventTime(Instant.now().toEpochMilli())
            .build();
        publisher.publish("tracking-events", event.getTrackingNumber().toString(), tracking);

        meterRegistry.counter("carrier.manifest.transmitted").increment();
        log.info("Manifest transmitted and OrderShipped published for orderId={}", event.getOrderId());
    }

    /**
     * Builds a minimal X12 856 Ship Notice body.
     * In production this is generated by a proper EDI library (smooks, Stedi, etc.)
     */
    private String buildX12_856(OrderPacked event) {
        return String.format(
            "ISA*00*          *00*          *ZZ*SHIPPER        *ZZ*CARRIER        *%s*%s*^*00501*000000001*0*P*:~\n" +
            "GS*SH*SHIPPER*CARRIER*%s*%s*1*X*005010X158A1~\n" +
            "ST*856*0001~\n" +
            "BSN*00*%s*%s*%s~\n" +
            "HL*1**S~\n" +
            "TD5**2*%s**%s~\n" +
            "SE*6*0001~\n" +
            "GE*1*1~\n" +
            "IEA*1*000000001~\n",
            Instant.now().toString().substring(2, 8).replace("-", ""),  // date
            Instant.now().toString().substring(11, 16).replace(":", ""), // time
            Instant.now().toString().substring(2, 8).replace("-", ""),
            Instant.now().toString().substring(11, 16).replace(":", ""),
            event.getShipmentId(),
            Instant.now().toString().substring(0, 10).replace("-", ""),
            Instant.now().toString().substring(11, 16).replace(":", ""),
            event.getCarrier(),
            event.getTrackingNumber()
        );
    }
}
